[package]
name = "mimalloc-rs"
version = "0.1.0"
edition = "2021"
categories = ["memory-management"]
keywords = ["memory", "allocator", "mimalloc"]


[dependencies]
libc = "*"
libc-print = "*"
bitflags = "*"
ctor = "*"

[[example]]
name = "helloworld"


